apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: visual-expenses
build:
  artifacts:
    - image: piotrjwegrzyn/visual-expenses
      docker:
        dockerfile: Dockerfile
        target: dev
deploy:
  helm:
    releases:
      - name: visual-expenses
        namespace: visual-expenses
        createNamespace: true
        chartPath: helm
        setValueTemplates:
          image.tag: '{{.IMAGE_TAG}}'
portForward:
- resourceType: service
  resourceName: visual-expenses
  namespace: visual-expenses
  port: 80
