name: "Tests"

on:
  pull_request:
    branches: [ master ]

jobs:
  golang:
    runs-on: ubuntu-latest
    name: Go tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go build
      - run: go test -v -cover ./... -coverprofile coverage.out
      - uses: actions/upload-artifact@v4
        with:
          name: Go code coverage
          path: coverage.out
      - run: go tool cover -func coverage.out

